[server]
address = '0.0.0.0:3001'
log_level = 'info'
# If unset, we fall back to the `Host:` header
#url = 'http://127.0.0.1:3001'

[database]
connection_string = 'postgresql://user:pass@host:port/db'

[blockfrost]
project_id = 'preview_BLOCKFROST_PROJECT_ID'
nft_asset = '4213fc3eac8c781ac85514dd1de9aaabcd5a3a81cc2df4f413b9b295'

[hydra_platform]
max_concurrent_hydra_nodes = 2
cardano_signing_key = "./hydra-config/preview/_our-keys/payment/payment.sk"
commit_ada = 3.0
lovelace_per_request = 100_000
requests_per_microtransaction = 10
microtransactions_per_fanout = 2

[hydra_bridge]
max_concurrent_hydra_nodes = 2
cardano_signing_key = "./hydra-config/preview/_our-keys/payment/payment.sk"
commit_ada = 4.0
lovelace_per_request = 100_000
requests_per_microtransaction = 10
microtransactions_per_fanout = 3
